name: codezza
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icon plugin
  cupertino_icons: ^1.0.3
  ionicons: ^0.1.2
  font_awesome_flutter: ^9.0.0
  equatable: ^2.0.2
  flutter_form_builder: ^6.0.1
  flip_card: ^0.5.0

  # 로딩 화면 plugin
  flutter_native_splash: ^1.1.8+4

# 생성 명령어 flutter pub run flutter_native_splash:create
# 제거 명령어 flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#75F0AE"
  image: assets/images/Logo/Logo1.png
  android: true
  ios: false
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # 이미지
  assets:
    - assets/images/Item/HandMade.png
    - assets/images/Item/Tack.png
    - assets/images/Logo/Logo0.png
    - assets/images/Logo/Logo1.png
    - assets/images/Logo/Logo2.png
    - assets/images/Logo/Logo3.png
    - assets/images/Profile/profile1.png
    - assets/images/Profile/profile2.png
    - assets/images/Profile/user.png

  fonts:
    - family: GmarketSansBold
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf

    - family: GmarketSansLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf

    - family: GmarketSansMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf