name: codezza
description: A new Team Codezza Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  # icon plugin
  ionicons: ^0.1.2
  font_awesome_flutter: ^9.1.0

  extended_tabs: ^2.3.0
  flip_card: ^0.5.0
  dotted_border: ^2.0.0+1
  list_tile_switch: ^1.0.0
  flutter_form_builder: ^6.1.0+1
  flutter_speed_dial: ^4.4.0+1

  # 통신을 위한 plugin
  http: ^0.13.3
  equatable: ^2.0.3

  # session
  # flutter_session:
  shared_preferences: ^2.0.8

  # cookie
  cookie_jar: 3.0.1

  # 로딩 화면 plugin
  flutter_native_splash: ^1.2.4

  # 이미지
  image_picker:
  multi_image_picker:

  # 비디오
  video_player:

  # alert
  rflutter_alert: ^2.0.4

  # permission
  path_provider: ^2.0.5

  # image upload, resize
  photo_manager: 0.4.8
  photo: 0.4.8
  image: 3.0.7
  heic_to_jpg: 0.1.2
  # firebase_core: 0.4.0+8
  # firebase_storage: 3.0.4
  # image_cropper: 1.4.1

  # uuid
  uuid: ^3.0.4

  string_validator: ^0.3.0

  # ////////////////////
  animator:
  timeago:
  cached_network_image:
  geolocator: ^5.0.0

# 생성 명령어 flutter pub run flutter_native_splash:create
# 제거 명령어 flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#75F0AE"
  image: assets/images/Logo/Logo1.png
  android: true
  ios: false
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true

  # 이미지
  assets:
    - assets/images/Item/HandMade.png
    - assets/images/Item/Tack.png
    - assets/images/Logo/Logo0.png
    - assets/images/Logo/Logo1.png
    - assets/images/Logo/Logo2.png
    - assets/images/Logo/Logo3.png
    - assets/images/Profile/profile1.png
    - assets/images/Profile/profile2.png
    - assets/images/Profile/user.png
    - assets/images/background.png
    - assets/images/background_group.png

  # 폰트
  fonts:
    - family: GmarketSansBold
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf

    - family: GmarketSansLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf

    - family: GmarketSansMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
